version: '3.5'

services:
  wine-sales:
    build: .
    container_name: wine-sales
    ports:      
      - "5600:80"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord.conf:/etc/supervisord.conf
    environment:          
      DEBUG: 'True'
      DATABASE_PORT: "3306"
      BASE_URL: "http://localhost"
      

